### ISSUE TITLE
📆 Create and illustrate a roadmap

### ISSUE THREAD

**Issue by janhalen** [OS2sandbox/sandbox-samtale#9]
## 🎯 Objective:
To have a clear vision for the 0.9 and 1.0 releases we should create a roadmap and illustrate it

- [ ] Make a list in text format with tasks and deliveries with a date and relations / cronology
- [ ] Convert it to visually appealing diagrams

**Comment by janhalen** [comment]
@Tgjerulff 

I suggest we use the [Mermaid/Gantt illustrations](https://mermaid.js.org/syntax/gantt.html) built in to GitHub.

example diagram:
```mermaid
gantt
    title A Gantt Diagram
    %% This is a comment
    dateFormat YYYY-MM-DD
    section Section
        A task          :a1, 2014-01-01, 30d
        Another task    :after a1, 20d
    section Another
        Task in Another :2014-01-12, 12d
        another task    :24d

```

**Comment by janhalen** [comment]
To build the roadmap we need:

- A list of activities with [name, status(empty if not started), start-date and duration
and to complement the activitites:
- a list of milestones with [milestonename and delivery date]

The milestone name should follow semantic versioning like: `0.9-rc`

**Comment by janhalen** [comment]
We need to break down the following tasks into time estimates and to assign who is responsible for acting on them:

- [ ]  Create a contract framework and finish the contract
- [ ]  Sign the Contract
- [ ]  Completion and Delivery of a Service Level Agreement (SLA) (expected response times for changes, support etc.)
- [ ]  Buy and register the DNS name for os2samtale
- [ ]  Bind the DNS to Digitalist serviceprovider
- [ ]  Set up and register acces and identity management with Fælleskommunal Adgangsstyring

First draft attemtp at a timeline:

```mermaid
gantt
    title os2samtale Roadmap
    tickInterval 1week
    weekday monday
    dateFormat  DD-MM-YYYY
    axisFormat  %b-%y
    excludes    weekends


    section Milestones
    Go live 0.9 : milestone, m1, 19-02-2025, 1d

    section Activities

    Finish the ISO : active, iso1, 01-12-2024, 1d
    Create a contract framework  : contract1, after iso1, 15d
    Create a contract framework and finish the contract   : contract2, after contract1, 15d
    Contract Signing     : contract3, after contract2, 10d
    Completion and Delivery of a Service Level Agreement (SLA) : sla1, after contract3, 10d
    Buy and register the DNS name for os2samtale               : dns1, after sla1, 3d
    Set up and register acces and identity management with Fælleskommunal Adgangsstyring        : fk1, after dns1, 3d
```

**Comment by Tgjerulff** [comment]
@janhalen please incorporate the following suggestions for timeline activities post Go live 0.9. 

**March 1st - 30 days** 
1. Testphase 

**March 31st - 1 day**
1. User evaluation

**April 1st - 29 days**
2. Testphase 

**April 30th - 1 day** 
2. User evaluation 

**May 1st - 30 days**
3. Testphase (final)

**May 31st - 1 day**
3. User evaluation (final)

**June 1st - 14 days** 
Konfiguration OS2samtale 1.0

**June 15th - 1 day**
User acceptance test (UAT)

**June 16th - 14 days**
Project handover - From OS2project to OS2product

**July 1st - 90 days**
Expansion to new OS2products and hyper support phase

**Comment by Tgjerulff** [comment]
@janhalen I suggest the following configuration levels for OS2samtale 0.9 

**Level 1 - Product names**
1. OS2forms
1. OS2borgerPC

**Level 2 - Generic channels** 
1.2. Leverandørsamarbejde
1.2. Produktudvikling
1.2. Koordinering
1.2. Github
1.2. Udbredelse

**Comment by janhalen** [comment]
@Tgjerulff: Your excellent suggestion for a 1.0 Release roadmap, wrangled into a gantt:
([using mermaid gantt](https://mermaid.js.org/syntax/gantt.html)):  

I added activities for setting up a support organization and assigning a product coordinator / owner before 1.0 release.

```mermaid

gantt
        title os2samtale Roadmap Release 1.0
    tickInterval 1w
    weekday monday
    dateFormat  DD-MM-YYYY
    axisFormat  %b-%y
    excludes    weekends

    Section Milestones
    Release 1.0 : milestone, m1, after a5, 1d

    Section Organization<br>creation
    Establish support ressources :o1, 2025-03-01, 48d
    Establish product owner      :o2, after o1, 48d

    section Test Phase 1
    Testphase             :a1, 2025-03-01, 30d
    User evaluation       :e1, after a1  , 1d
    section Test Phase 2
    Testphase             :a2, after e1, 29d
    User evaluation       :e2, after a2  , 1d
    section Test Phase 3 (Final)
    Testphase (final)     :a3, after e2, 30d
    User evaluation (final):after a3  , 1d
    section Configuration and Testing
    Konfiguration OS2samtale 1.0 :a4, 2025-07-01, 14d
    User acceptance test (UAT)   :uat, after a4, 1d
    section Project Handover
    Project handover - From OS2project to OS2product :a5, after uat, 14d
    section Expansion Phase
    Expansion to new OS2products and hyper support phase :a6, after a5, 90d

```

@zorp & @mikkeschiren: Suggested activities for spring 2025, what is lacking is a project coordinater after @Tgjerulff leaves us and setting up an organization for application support.

**Comment by janhalen** [comment]
@ChatBotBerg: Here is the old roadmap work... now pretty outdated.
